package system;
/** Generated by YAKINDU Statechart Tools code generator. */

import com.yakindu.core.ICycleBased;
import com.yakindu.core.IStatemachine;
import com.yakindu.core.ITimed;
import com.yakindu.core.ITimerService;
import com.yakindu.core.rx.Observable;

public class TrafficLight implements IStatemachine, ITimed, ICycleBased {
	public static class Lights {
		private boolean red;
		
		public boolean getRed() {
			return red;
		}
		
		public void setRed(boolean value) {
			this.red = value;
		}
		
		private boolean yellow;
		
		public boolean getYellow() {
			return yellow;
		}
		
		public void setYellow(boolean value) {
			this.yellow = value;
		}
		
		private boolean green;
		
		public boolean getGreen() {
			return green;
		}
		
		public void setGreen(boolean value) {
			this.green = value;
		}
		
	}
	
	public static class Config {
		private long releasePeriod;
		
		public long getReleasePeriod() {
			return releasePeriod;
		}
		
		public void setReleasePeriod(long value) {
			this.releasePeriod = value;
		}
		
		private long preparePeriod;
		
		public long getPreparePeriod() {
			return preparePeriod;
		}
		
		public void setPreparePeriod(long value) {
			this.preparePeriod = value;
		}
		
	}
	
	private static class EvBuf {
		private boolean switchOn;
		private boolean switchOff;
		private boolean attention;
		private boolean block;
		private boolean release;
	}
	private static class TimeEventsEvBuf {
		private boolean trafficLight_main_On_main_Released_time_event_0;
		private boolean trafficLight_main_On_main_Attention_time_event_0;
		private boolean trafficLight_main_On_main_PrepareBlock_time_event_0;
	}
	private static class TrafficLightEvBuf {
		private EvBuf iface = new EvBuf();
		private TimeEventsEvBuf timeEvents = new TimeEventsEvBuf();
	}
	protected Lights lights;
	
	protected Config config;
	
	public enum State {
		MAIN_OFF,
		MAIN_ON,
		MAIN_ON_MAIN_BLOCKED,
		MAIN_ON_MAIN_RELEASED,
		MAIN_ON_MAIN_ATTENTION,
		MAIN_ON_MAIN_PREPAREBLOCK,
		$NULLSTATE$
	};
	
	private final State[] stateVector = new State[1];
	
	private int nextStateIndex;
	
	private ITimerService timerService;
	
	private final boolean[] timeEvents = new boolean[3];
	
	public static final boolean oN = true;
	
	protected boolean getON() {
		return oN;
	}
	
	
	public static final boolean oFF = false;
	
	protected boolean getOFF() {
		return oFF;
	}
	
	
	private TrafficLightEvBuf current = new TrafficLightEvBuf();
	
	private boolean isExecuting;
	
	protected boolean getIsExecuting() {
		return isExecuting;
	}
	
	protected void setIsExecuting(boolean value) {
		this.isExecuting = value;
	}
	public TrafficLight() {
		lights = new Lights();
		config = new Config();
		for (int i = 0; i < 1; i++) {
			stateVector[i] = State.$NULLSTATE$;
		}
		
		clearInEvents();
		
		lights.setRed(false);
		
		lights.setYellow(false);
		
		lights.setGreen(false);
		
		config.setReleasePeriod(6);
		
		config.setPreparePeriod(2);
		
		isExecuting = false;
	}
	
	public void enter() {
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		
		
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		enterSequence_main_default();
		isExecuting = false;
	}
	
	public void exit() {
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		exitSequence_main();
		isExecuting = false;
	}
	
	public void runCycle() {
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		
		
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		swapInEvents();
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
			case MAIN_OFF:
				main_Off_react(true);
				break;
			case MAIN_ON_MAIN_BLOCKED:
				main_On_main_Blocked_react(true);
				break;
			case MAIN_ON_MAIN_RELEASED:
				main_On_main_Released_react(true);
				break;
			case MAIN_ON_MAIN_ATTENTION:
				main_On_main_Attention_react(true);
				break;
			case MAIN_ON_MAIN_PREPAREBLOCK:
				main_On_main_PrepareBlock_react(true);
				break;
			default:
				// $NULLSTATE$
			}
		}
		
		isExecuting = false;
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public boolean isActive() {
		return stateVector[0] != State.$NULLSTATE$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public boolean isFinal() {
		return false;
	}
	private void swapInEvents() {
		current.iface.switchOn = switchOn;
		switchOn = false;
		
		current.iface.switchOff = switchOff;
		switchOff = false;
		
		current.iface.attention = attention;
		attention = false;
		
		current.iface.block = block;
		block = false;
		
		current.iface.release = release;
		release = false;
		
		current.timeEvents.trafficLight_main_On_main_Released_time_event_0 = timeEvents[0];
		timeEvents[0] = false;
		
		current.timeEvents.trafficLight_main_On_main_Attention_time_event_0 = timeEvents[1];
		timeEvents[1] = false;
		
		current.timeEvents.trafficLight_main_On_main_PrepareBlock_time_event_0 = timeEvents[2];
		timeEvents[2] = false;
	}
	
	private void clearInEvents() {
		switchOn = false;
		switchOff = false;
		attention = false;
		block = false;
		release = false;
		timeEvents[0] = false;
		timeEvents[1] = false;
		timeEvents[2] = false;
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public boolean isStateActive(State state) {
	
		switch (state) {
		case MAIN_OFF:
			return stateVector[0] == State.MAIN_OFF;
		case MAIN_ON:
			return stateVector[0].ordinal() >= State.
					MAIN_ON.ordinal()&& stateVector[0].ordinal() <= State.MAIN_ON_MAIN_PREPAREBLOCK.ordinal();
		case MAIN_ON_MAIN_BLOCKED:
			return stateVector[0] == State.MAIN_ON_MAIN_BLOCKED;
		case MAIN_ON_MAIN_RELEASED:
			return stateVector[0] == State.MAIN_ON_MAIN_RELEASED;
		case MAIN_ON_MAIN_ATTENTION:
			return stateVector[0] == State.MAIN_ON_MAIN_ATTENTION;
		case MAIN_ON_MAIN_PREPAREBLOCK:
			return stateVector[0] == State.MAIN_ON_MAIN_PREPAREBLOCK;
		default:
			return false;
		}
	}
	
	public void setTimerService(ITimerService timerService) {
		this.timerService = timerService;
	}
	
	public ITimerService getTimerService() {
		return timerService;
	}
	
	public void raiseTimeEvent(int eventID) {
		timeEvents[eventID] = true;
	}
	
	public Lights lights() {
		return lights;
	}
	
	public Config config() {
		return config;
	}
	
	private boolean switchOn;
	
	
	public void raiseSwitchOn() {
		switchOn = true;
	}
	
	private boolean switchOff;
	
	
	public void raiseSwitchOff() {
		switchOff = true;
	}
	
	private boolean attention;
	
	
	public void raiseAttention() {
		attention = true;
	}
	
	private boolean block;
	
	
	public void raiseBlock() {
		block = true;
	}
	
	private boolean release;
	
	
	public void raiseRelease() {
		release = true;
	}
	
	private boolean blocked;
	
	
	protected void raiseBlocked() {
		blocked = true;
		blockedObservable.next(null);
	}
	
	private Observable<Void> blockedObservable = new Observable<Void>();
	
	public Observable<Void> getBlocked() {
		return blockedObservable;
	}
	
	private boolean released;
	
	
	protected void raiseReleased() {
		released = true;
		releasedObservable.next(null);
	}
	
	private Observable<Void> releasedObservable = new Observable<Void>();
	
	public Observable<Void> getReleased() {
		return releasedObservable;
	}
	
	/* Entry action for state 'Off'. */
	private void entryAction_main_Off() {
		lights.setRed(oFF);
		
		lights.setGreen(oFF);
		
		lights.setYellow(oFF);
	}
	
	/* Entry action for state 'Blocked'. */
	private void entryAction_main_On_main_Blocked() {
		lights.setRed(oN);
		
		raiseBlocked();
	}
	
	/* Entry action for state 'Released'. */
	private void entryAction_main_On_main_Released() {
		timerService.setTimer(this, 0, (config.getReleasePeriod() * 1000), false);
		
		lights.setGreen(oN);
		
		raiseReleased();
	}
	
	/* Entry action for state 'Attention'. */
	private void entryAction_main_On_main_Attention() {
		timerService.setTimer(this, 1, 500, true);
		
		lights.setYellow(oN);
	}
	
	/* Entry action for state 'PrepareBlock'. */
	private void entryAction_main_On_main_PrepareBlock() {
		timerService.setTimer(this, 2, (config.getPreparePeriod() * 1000), false);
		
		lights.setYellow(oN);
	}
	
	/* Exit action for state 'Blocked'. */
	private void exitAction_main_On_main_Blocked() {
		lights.setRed(oFF);
	}
	
	/* Exit action for state 'Released'. */
	private void exitAction_main_On_main_Released() {
		timerService.unsetTimer(this, 0);
		
		lights.setGreen(oFF);
	}
	
	/* Exit action for state 'Attention'. */
	private void exitAction_main_On_main_Attention() {
		timerService.unsetTimer(this, 1);
		
		lights.setYellow(oFF);
	}
	
	/* Exit action for state 'PrepareBlock'. */
	private void exitAction_main_On_main_PrepareBlock() {
		timerService.unsetTimer(this, 2);
		
		lights.setYellow(oFF);
	}
	
	/* 'default' enter sequence for state Off */
	private void enterSequence_main_Off_default() {
		entryAction_main_Off();
		nextStateIndex = 0;
		stateVector[0] = State.MAIN_OFF;
	}
	
	/* 'default' enter sequence for state On */
	private void enterSequence_main_On_default() {
		enterSequence_main_On_main_default();
	}
	
	/* 'default' enter sequence for state Blocked */
	private void enterSequence_main_On_main_Blocked_default() {
		entryAction_main_On_main_Blocked();
		nextStateIndex = 0;
		stateVector[0] = State.MAIN_ON_MAIN_BLOCKED;
	}
	
	/* 'default' enter sequence for state Released */
	private void enterSequence_main_On_main_Released_default() {
		entryAction_main_On_main_Released();
		nextStateIndex = 0;
		stateVector[0] = State.MAIN_ON_MAIN_RELEASED;
	}
	
	/* 'default' enter sequence for state Attention */
	private void enterSequence_main_On_main_Attention_default() {
		entryAction_main_On_main_Attention();
		nextStateIndex = 0;
		stateVector[0] = State.MAIN_ON_MAIN_ATTENTION;
	}
	
	/* 'default' enter sequence for state PrepareBlock */
	private void enterSequence_main_On_main_PrepareBlock_default() {
		entryAction_main_On_main_PrepareBlock();
		nextStateIndex = 0;
		stateVector[0] = State.MAIN_ON_MAIN_PREPAREBLOCK;
	}
	
	/* 'default' enter sequence for region main */
	private void enterSequence_main_default() {
		react_main__entry_Default();
	}
	
	/* 'default' enter sequence for region main */
	private void enterSequence_main_On_main_default() {
		react_main_On_main__entry_Default();
	}
	
	/* Default exit sequence for state Off */
	private void exitSequence_main_Off() {
		nextStateIndex = 0;
		stateVector[0] = State.$NULLSTATE$;
	}
	
	/* Default exit sequence for state On */
	private void exitSequence_main_On() {
		exitSequence_main_On_main();
	}
	
	/* Default exit sequence for state Blocked */
	private void exitSequence_main_On_main_Blocked() {
		nextStateIndex = 0;
		stateVector[0] = State.$NULLSTATE$;
		
		exitAction_main_On_main_Blocked();
	}
	
	/* Default exit sequence for state Released */
	private void exitSequence_main_On_main_Released() {
		nextStateIndex = 0;
		stateVector[0] = State.$NULLSTATE$;
		
		exitAction_main_On_main_Released();
	}
	
	/* Default exit sequence for state Attention */
	private void exitSequence_main_On_main_Attention() {
		nextStateIndex = 0;
		stateVector[0] = State.$NULLSTATE$;
		
		exitAction_main_On_main_Attention();
	}
	
	/* Default exit sequence for state PrepareBlock */
	private void exitSequence_main_On_main_PrepareBlock() {
		nextStateIndex = 0;
		stateVector[0] = State.$NULLSTATE$;
		
		exitAction_main_On_main_PrepareBlock();
	}
	
	/* Default exit sequence for region main */
	private void exitSequence_main() {
		switch (stateVector[0]) {
		case MAIN_OFF:
			exitSequence_main_Off();
			break;
		case MAIN_ON_MAIN_BLOCKED:
			exitSequence_main_On_main_Blocked();
			break;
		case MAIN_ON_MAIN_RELEASED:
			exitSequence_main_On_main_Released();
			break;
		case MAIN_ON_MAIN_ATTENTION:
			exitSequence_main_On_main_Attention();
			break;
		case MAIN_ON_MAIN_PREPAREBLOCK:
			exitSequence_main_On_main_PrepareBlock();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region main */
	private void exitSequence_main_On_main() {
		switch (stateVector[0]) {
		case MAIN_ON_MAIN_BLOCKED:
			exitSequence_main_On_main_Blocked();
			break;
		case MAIN_ON_MAIN_RELEASED:
			exitSequence_main_On_main_Released();
			break;
		case MAIN_ON_MAIN_ATTENTION:
			exitSequence_main_On_main_Attention();
			break;
		case MAIN_ON_MAIN_PREPAREBLOCK:
			exitSequence_main_On_main_PrepareBlock();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_main__entry_Default() {
		enterSequence_main_Off_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_On_main__entry_Default() {
		enterSequence_main_On_main_Attention_default();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean main_Off_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (current.iface.switchOn) {
					exitSequence_main_Off();
					enterSequence_main_On_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean main_On_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (current.iface.switchOff) {
					exitSequence_main_On();
					enterSequence_main_Off_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean main_On_main_Blocked_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (main_On_react(try_transition)==false) {
				if (current.iface.release) {
					exitSequence_main_On_main_Blocked();
					enterSequence_main_On_main_Released_default();
				} else {
					if (current.iface.attention) {
						exitSequence_main_On_main_Blocked();
						enterSequence_main_On_main_Attention_default();
					} else {
						did_transition = false;
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean main_On_main_Released_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (main_On_react(try_transition)==false) {
				if (current.timeEvents.trafficLight_main_On_main_Released_time_event_0) {
					exitSequence_main_On_main_Released();
					enterSequence_main_On_main_PrepareBlock_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean main_On_main_Attention_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (main_On_react(try_transition)==false) {
				if (current.iface.block) {
					exitSequence_main_On_main_Attention();
					enterSequence_main_On_main_Blocked_default();
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			if (current.timeEvents.trafficLight_main_On_main_Attention_time_event_0) {
				lights.setYellow(!lights.yellow);
			}
		}
		return did_transition;
	}
	
	private boolean main_On_main_PrepareBlock_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (main_On_react(try_transition)==false) {
				if (current.timeEvents.trafficLight_main_On_main_PrepareBlock_time_event_0) {
					exitSequence_main_On_main_PrepareBlock();
					enterSequence_main_On_main_Blocked_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
}
